### ISSUE TITLE
Support for AArch64 (arm64)

### ISSUE THREAD

**Issue by zhongweiy** [hypriot/golang-armbuilds#3]
Hi, there, will this project support AArch64 building?

**Comment by DieterReuter** [comment]
Yes of course. I already have a tarball, will upload it later.

**Comment by zhongweiy** [comment]
Great. And it will be better to mention it in README.

**Comment by DieterReuter** [comment]
I just uploaded a pre-compiled tarball for `arm64` aka `aarch64` for Go1.5.1 at https://github.com/hypriot/golang-armbuilds/releases/tag/v1.5.1.

And updated the README accordingly.

**Comment by zhongweiy** [comment]
Thanks!

**Comment by DieterReuter** [comment]
You're welcome.

If you like, you could also share some of your experiences with our builds and for what ARM devices you're using it. Would love to get feedback and I'm still looking for a good ARM64 dev machine too.

**Comment by zhongweiy** [comment]
I was building go for AArch64 on Hikey board manually by following http://dave.cheney.net/tag/arm64. I find it is easy to get it wrong. Having a binary release would definitely help a lot!

And I'll post feedback when I use this project.

**Comment by alexandruavadanii** [comment]
Big thanks for an older precompiled binary of 1.5.2 (AArch64), hard to find and a pain to build since upstream moved to newer versions.
For the record, building `heka` (also obsolete at this time) on Cavium ThunderX (48 cores), which only supports go 1.4...1.5; for cloud monitoring tools we want to support in OPNFV.

**Comment by DieterReuter** [comment]
Thanks for the kind words!
